workflows:
  android-build:
    name: Android APK Build
    max_build_duration: 60
    environment:
      vars:
        # Optional: for signing, if needed
        ANDROID_KEYSTORE_PASSWORD: Encrypted
        ANDROID_KEY_PASSWORD: Encrypted
    scripts:
      - name: Clean project
        script: ./gradlew clean
      - name: Build debug APK
        script: ./gradlew assembleDebug
      # Optional release APK
      #- name: Build release APK
      #  script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk