workflows:
  android-build:
    name: Android APK Build
    max_build_duration: 60
    environment:
      flutter: none # Not a Flutter project
      vars:
        ANDROID_KEYSTORE_PASSWORD: Encrypted
        ANDROID_KEY_PASSWORD: Encrypted
    scripts:
      - name: Clean project
        script: ./gradlew clean
      - name: Build debug APK
        script: ./gradlew assembleDebug
      # Optional: Build release APK
      #- name: Build release APK
      #  script: ./gradlew assembleRelease
    artifacts:
      - build/app/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com