workflows:
  android-build:
    name: IoTControllerApp Build
    max_build_duration: 60
    environment:
      vars:
        ANDROID_KEYSTORE_PASSWORD: Encrypted
        ANDROID_KEY_PASSWORD: Encrypted
        ANDROID_KEY_ALIAS: Encrypted

    scripts:
      - name: Checkout repository
        script: git clone $CM_REPO_BRANCH

      - name: Set up JDK
        script: sudo apt install openjdk-17-jdk -y

      - name: Set up Android SDK
        script: yes | sdkmanager --licenses

      - name: Clean project
        script: ./gradlew clean

      - name: Download offline map if missing
        script: |
          MDTILES_DIR="app/build/offline_mdtiles"
          if [ ! -d "$MDTILES_DIR" ] || [ -z "$(ls -A $MDTILES_DIR)" ]; then
            echo "MDTiles not found, downloading..."
            ./gradlew downloadMdTiles
          else
            echo "MDTiles already exist, skipping download."
          fi

      - name: Build APK with branch-based naming
        script: |
          BUILD_NAME=""
          if [ "$CM_BRANCH" = "main" ]; then
            echo "Building release APK on main branch..."
            ./gradlew assembleRelease -x lint -x compileReleaseKotlin
            BUILD_NAME="app/build/outputs/flutter-apk/app-release.apk"
            mv $BUILD_NAME "app/build/outputs/flutter-apk/app-release-main-${CM_BUILD_NUMBER}.apk"
          else
            echo "Building debug APK on branch $CM_BRANCH..."
            ./gradlew assembleDebug -x lint -x compileDebugKotlin
            BUILD_NAME="app/build/outputs/flutter-apk/app-debug.apk"
            mv $BUILD_NAME "app/build/outputs/flutter-apk/app-debug-${CM_BRANCH}-${CM_BUILD_NUMBER}.apk"
          fi

    cache:
      paths:
        - app/build/offline_mdtiles
        - ~/.gradle
        - ~/.pub-cache

    artifacts:
      - app/build/outputs/**/*.apk