workflows:
  release-build:
    name: IoTControllerApp Release Build
    max_build_duration: 60
    environment:
      vars:
        ANDROID_KEYSTORE_PASSWORD: Encrypted
        ANDROID_KEY_PASSWORD: Encrypted
        ANDROID_KEY_ALIAS: Encrypted

    triggering:
      events:
        - push
      branches:
        only:
          - main

    scripts:
      - name: Accept Android SDK licenses
        script: yes | sdkmanager --licenses

      - name: Clean project
        script: ./gradlew clean

      - name: Download offline MDTiles if missing
        script: |
          MDTILES_DIR="app/build/offline_mdtiles"
          if [ ! -d "$MDTILES_DIR" ] || [ -z "$(ls -A $MDTILES_DIR)" ]; then
            echo "MDTiles not found, downloading..."
            ./gradlew downloadMdTiles
          else
            echo "MDTiles already exist, skipping download."
          fi

      - name: Build signed release APK
        script: |
          echo "Building signed release APK on main branch..."
          ./gradlew assembleRelease \
            -Pandroid.keystorePassword=$ANDROID_KEYSTORE_PASSWORD \
            -Pandroid.keyPassword=$ANDROID_KEY_PASSWORD \
            -Pandroid.keyAlias=$ANDROID_KEY_ALIAS \
            -x lint -x compileReleaseKotlin

    artifacts:
      - app/build/outputs/**/*.apk

    cache:
      paths:
        - app/build/offline_mdtiles
        - ~/.gradle
        - ~/.pub-cache