workflows:
  android-build:
    name: IoTControllerApp Build
    max_build_duration: 60
    environment:
      vars:
        ANDROID_KEYSTORE_PASSWORD: Encrypted
        ANDROID_KEY_PASSWORD: Encrypted
        ANDROID_KEY_ALIAS: Encrypted

    scripts:
      - name: Set up JDK
        script: sudo apt install openjdk-17-jdk -y

      - name: Set up Android SDK
        script: yes | sdkmanager --licenses

      - name: Clean project
        script: ./gradlew clean

      - name: Download offline MDTiles if missing
        script: |
          MDTILES_DIR="app/build/offline_mdtiles"
          if [ ! -d "$MDTILES_DIR" ] || [ -z "$(ls -A $MDTILES_DIR)" ]; then
            echo "MDTiles not found, downloading..."
            ./gradlew downloadMdTiles
          else
            echo "MDTiles already exist, skipping download."
          fi

      - name: Build APK
        script: |
          if [ "$CM_BRANCH" = "main" ]; then
            echo "Building release APK on main branch..."
            ./gradlew assembleRelease -x lint -x compileReleaseKotlin
          else
            echo "Building debug APK on branch $CM_BRANCH..."
            ./gradlew assembleDebug -x lint -x compileDebugKotlin

    cache:
      key: android-build-cache
      directories:
        - app/build/offline_mdtiles
        - ~/.gradle
        - ~/.pub-cache

    artifacts:
      - app/build/outputs/**/*.apk