workflows:
  android-build:
    name: IoTControllerApp Build
    max_build_duration: 60
    environment:
      vars:
        # Optional: for signing release APK
        ANDROID_KEYSTORE_PASSWORD: Encrypted
        ANDROID_KEY_PASSWORD: Encrypted
        ANDROID_KEY_ALIAS: Encrypted
    scripts:
      - name: Clean project
        script: ./gradlew clean

      - name: Download mbtiles map
        script: |
          mkdir -p app/src/main/assets/maps
          curl -L "https://we.tl/t-CAaLcBJ2Ot" -o app/src/main/assets/maps/offline_india.mbtiles
          ls -lh app/src/main/assets/maps/

      - name: Build debug APK
        script: ./gradlew assembleDebug

      - name: Build release APK
        script: ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/**/*.apk