workflows:
  android-build:
    name: IoTControllerApp Build
    max_build_duration: 60
    environment:
      vars:
        ANDROID_KEYSTORE_PASSWORD: Encrypted
        ANDROID_KEY_PASSWORD: Encrypted
        ANDROID_KEY_ALIAS: Encrypted

    triggering:
      events:
        - push
        - pull_request

    scripts:
      - name: Checkout repository
        script: git clone $CM_REPO_BRANCH

      - name: Set up JDK and Android SDK
        script: |
          echo "Using Codemagic's preinstalled JDK and Android SDK"
          java -version
          sdkmanager --version
          yes | sdkmanager --licenses

      - name: Clean project
        script: ./gradlew clean

      - name: Download offline map if missing
        script: |
          MDTILES_DIR="$CM_BUILD_DIR/app/build/offline_mdtiles"
          if [ ! -d "$MDTILES_DIR" ] || [ -z "$(ls -A $MDTILES_DIR)" ]; then
            echo "MDTiles not found, downloading..."
            ./gradlew downloadMdTiles
          else
            echo "MDTiles already exist, skipping download."
          fi

      - name: Build APK
        script: |
          if [ "$CM_BRANCH" = "main" ]; then
            echo "Building release APK on main branch..."
            ./gradlew assembleRelease -x lint -x compileReleaseKotlin
          else
            echo "Building debug APK on branch $CM_BRANCH..."
            ./gradlew assembleDebug -x lint -x compileDebugKotlin
          fi

    cache:
      directories:
        - ~/.gradle
        - ~/.pub-cache

    artifacts:
      - app/build/outputs/**/*.apk