workflows:
  android-build:
    name: IoTControllerApp Build
    max_build_duration: 60
    environment:
      vars:
        ANDROID_KEYSTORE_PASSWORD: Encrypted
        ANDROID_KEY_PASSWORD: Encrypted
        ANDROID_KEY_ALIAS: Encrypted

    scripts:
      - name: Clean project
        script: ./gradlew clean

      - name: Download offline map if missing
        script: |
          MDTILES_DIR="app/src/main/assets/maps"
          if [ ! -d "$MDTILES_DIR" ] || [ -z "$(ls -A $MDTILES_DIR)" ]; then
            echo "MDTiles not found, downloading..."
            ./gradlew downloadMdTiles
          else
            echo "MDTiles already exist, skipping download."
          fi

      - name: Build APK
        script: |
          if [ "$CM_BRANCH" = "main" ]; then
            echo "Building release APK..."
            ./gradlew assembleRelease -x lint
          else
            echo "Building debug APK..."
            ./gradlew assembleDebug -x lint
          fi

    artifacts:
      - app/build/outputs/**/*.apk